# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login
      inputs:
        containerRegistry: 'docker-registry-alexoswald'
        command: 'login'
    - task: CmdLine@2
      displayName: Build
      inputs:
        script: |
          docker run --privileged --rm tonistiigi/binfmt --install arm64
          docker run --privileged --rm tonistiigi/binfmt
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 \
            -t calendardisplay:$(build.buildNumber) \
            -t calendardisplay:latest \
            --push \
            CalendarDisplay/Dockerfile
