version: '3.8'

services:
  calendardisplay:
    build:
      context: '.'
      dockerfile : 'CalendarDisplay/Dockerfile'
    container_name: 'calendar_display'
    restart: 'unless-stopped'
    ports:
      - '5000:443'
    volumes:
      - './configuration/:/configuration/' # cert location
    environment:
      - 'AzureAd__Instance=https://login.microsoftonline.com/'
      - 'AzureAd__TenantId=common'
      - 'AzureAd__ClientId=${AZUREAD_CLIENTID}'
      - 'AzureAd__ClientSecret=${AZUREAD_CLIENTSECRET}'
      - 'ASPNETCORE_ENVIRONMENT=Production'
      - 'ASPNETCORE_URLS=https://+:443'
      - 'ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}'
      - 'ASPNETCORE_Kestrel__Certificates__Default__Path=${CERT_PATH}'
      - 'TodoListOptions_UpdateFrequency=3600'
      - 'TodoListOptions_TodoLists_2_Name=${TODOLISTS_2_NAME}'
      - 'TodoListOptions_TodoLists_1_Name=${TODOLISTS_1_NAME}'
      - 'TodoListOptions_TodoLists_0_Name=${TODOLISTS_0_NAME}'
      - 'CountdownOptions_UpdateFrequency=86400'
      - 'CountdownOptions_LookupMonths=24'
      - 'CountdownOptions_CountdownCount=3'
      - 'CountdownOptions_CalendarName=Vacations'
      - 'CalendarOptions_UpdateFrequency=3600'
      - 'CalendarOptions_Calendars_7_TextColor=black'
      - 'CalendarOptions_Calendars_7_Name=${CALENDARS_7_NAME}'
      - 'CalendarOptions_Calendars_7_BackgroundColor=limegreen'
      - 'CalendarOptions_Calendars_6_TextColor=white'
      - 'CalendarOptions_Calendars_6_Name=${CALENDARS_6_NAME}'
      - 'CalendarOptions_Calendars_6_BackgroundColor=deeppink'
      - 'CalendarOptions_Calendars_5_TextColor=black'
      - 'CalendarOptions_Calendars_5_Name=${CALENDARS_5_NAME}'
      - 'CalendarOptions_Calendars_5_BackgroundColor=turquoise'
      - 'CalendarOptions_Calendars_4_TextColor=white'
      - 'CalendarOptions_Calendars_4_Name=${CALENDARS_4_NAME}'
      - 'CalendarOptions_Calendars_4_BackgroundColor=orangered'
      - 'CalendarOptions_Calendars_3_TextColor=black'
      - 'CalendarOptions_Calendars_3_Name=Vacations'
      - 'CalendarOptions_Calendars_3_BackgroundColor=yellow'
      - 'CalendarOptions_Calendars_2_TextColor=white'
      - 'CalendarOptions_Calendars_2_Name=Seattle Seahawks'
      - 'CalendarOptions_Calendars_2_BackgroundColor=navy'
      - 'CalendarOptions_Calendars_1_TextColor=white'
      - 'CalendarOptions_Calendars_1_Name=United States holidays'
      - 'CalendarOptions_Calendars_1_BackgroundColor=maroon'
      - 'CalendarOptions_Calendars_0_TextColor=white'
      - 'CalendarOptions_Calendars_0_Name=Calendar'
      - 'CalendarOptions_Calendars_0_BackgroundColor=indigo'